### ISSUE TITLE
Shapefile upload fails for dBASE IV

### ISSUE THREAD

**Issue by popensesame** [nemac/NFWF_tool#207]
A small percentage of shapefile uploads will fail. The only one we know of is shapefiles downloaded from geojson.io.

This problem seems to occur because the shapefile parser we are using, mbostock/shapefile, only parses dbf files which are implemented with dBASE III.

I will be adding a shapefile known to fail to the test/assets folder (from geojson.io).

Shapefile implementations that need testing:

- [ ] ArcMap
- [x] ArcGIS Pro
- [x] QGIS

**Comment by daveism** [comment]
Closing, this ill be resolved in v2 currently being worked on.
