### ISSUE TITLE
Double Clicking on map makes a Promise throw does not have cancel error

### ISSUE THREAD

**Issue by frimmel** [nemac/NFWF_tool#35]
Console displays the following message 

Unhandled promise rejection Cancel {message: "Cancelled Ongoing Request"}
  | (anonymous) | @ | es6.promise.js:110
  | module.exports | @ | _perform.js:5
  | (anonymous) | @ | es6.promise.js:104
  | module.exports | @ | _invoke.js:8
  | queue.(anonymous function) | @ | _task.js:38
  | run | @ | _task.js:23
  | listener | @ | _task.js:27

**Comment by daveism** [comment]
commit e42e11dfaf5d37ab22538bd52300710e3483818a closes this.

**Comment by daveism** [comment]
commit e42e11dfaf5d37ab22538bd52300710e3483818a closes this.
